height: 300px
menubar: false
statusbar: false
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
plugins:
  - paste
  - table
  - insertdatetime
insertdate_dateformat: "%Y-%m-%d"
paste_auto_cleanup_on_paste : true
paste_remove_styles: true
paste_remove_styles_if_webkit: true
paste_strip_class_attributes: true
oninit: function (ed) { ed.pasteAsPlainText = true; }
paste_text_sticky: true

